name: Publish orienfish/pytorch:stam-ubuntu16.04

on:
  push:
    branches:
    - master
    paths:
    - dockerfiles/stam-ubuntu16.04/*
    - .github/workflows/publish_stam-ubuntu16.04.yml

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        repository: orienfish/pytorch
        tags: stam-ubuntu16.04,1.4.0-nocuda
        path: dockerfiles/stam-ubuntu16.04
